baseURL = 'https://newmilkiceonwall.github.io/'
title = "墙上的新牛奶冰"
theme = "coder"
languagecode = "zh"
defaultcontentlanguage = "zh-cn"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
  author = "Newmilkiceonwall"
  description = "Newmilkiceonwall's personal website"
  keywords = "blog,personal"
  avatarurl = "/img/avatar.png"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/img/32x32.png"
  favicon_16 = "/img/16x16.png"

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/newmilkiceonwall/"
#[[params.social]]
  #name = "Gitlab"
  #icon = "fa fa-gitlab fa-2x"
  #weight = 2
  #url = "https://gitlab.com/johndoe/"

# Menu links
[[menu.main]]
  name = "博客"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "关于"
  weight = 2
  url = "about/about"

defaultContentLanguage = 'zh-cn'
[languages]
  [languages.zh-cn]
    title = '墙上的新牛奶冰'
    weight = 1
    [languages.zh-cn.params]
      author = '墙上的新牛奶冰'
      info = "哪条路都不好走，啥子命我都不抗拒。"
      description = "墙上的新牛奶冰的个人小站。"
    [[languages.zh-cn.menu.main]]
      name = "博客"
      weight = 1
      url  = "posts/"
    [[languages.zh-cn.menu.main]]
      name = "关于"
      weight = 2
      url = "about/about"
    [[languages.zh-cn.menu.main]]
      name = "EN"
      weight = 3   
      url = "en"
  [languages.en]
    title = 'Newmilkiceonwall'
    weight = 2
    [languages.en.params]
      author = 'Newmilkiceonwall'
      info = "Every road is fraught, yet I embrace whatever destiny presents."
      description = "Newmilkiceonwall's personal blog."
    [[languages.en.menu.main]]
      name = "Blog"
      weight = 1
      url  = "posts/"
    [[languages.en.menu.main]]
      name = "About"
      weight = 2
      url = "about/about"
    [[languages.en.menu.main]]
      name = "中文"
      weight = 3
      url = ".."
